//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Speak.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class SpeakLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		SAYS=1, WORD=2, TEXT=3, WHITESPACE=4, NEWLINE=5;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"LOWERCASE", "UPPERCASE", "SAYS", "WORD", "TEXT", "WHITESPACE", "NEWLINE"
	};


	public SpeakLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SpeakLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
	};
	private static readonly string[] _SymbolicNames = {
		null, "SAYS", "WORD", "TEXT", "WHITESPACE", "NEWLINE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Speak.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SpeakLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\a', '\x36', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x6', '\x5', '\x1A', 
		'\n', '\x5', '\r', '\x5', '\xE', '\x5', '\x1B', '\x3', '\x6', '\x3', '\x6', 
		'\a', '\x6', ' ', '\n', '\x6', '\f', '\x6', '\xE', '\x6', '#', '\v', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x6', '\a', '(', '\n', '\a', 
		'\r', '\a', '\xE', '\a', ')', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x5', 
		'\b', '/', '\n', '\b', '\x3', '\b', '\x3', '\b', '\x6', '\b', '\x33', 
		'\n', '\b', '\r', '\b', '\xE', '\b', '\x34', '\x3', '!', '\x2', '\t', 
		'\x3', '\x2', '\x5', '\x2', '\a', '\x3', '\t', '\x4', '\v', '\x5', '\r', 
		'\x6', '\xF', '\a', '\x3', '\x2', '\x5', '\x3', '\x2', '\x63', '|', '\x3', 
		'\x2', '\x43', '\\', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x2', ':', 
		'\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x3', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x5', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\a', '\x15', '\x3', '\x2', '\x2', '\x2', '\t', '\x19', '\x3', '\x2', 
		'\x2', '\x2', '\v', '\x1D', '\x3', '\x2', '\x2', '\x2', '\r', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\xF', '\x32', '\x3', '\x2', '\x2', '\x2', '\x11', 
		'\x12', '\t', '\x2', '\x2', '\x2', '\x12', '\x4', '\x3', '\x2', '\x2', 
		'\x2', '\x13', '\x14', '\t', '\x3', '\x2', '\x2', '\x14', '\x6', '\x3', 
		'\x2', '\x2', '\x2', '\x15', '\x16', '\a', '<', '\x2', '\x2', '\x16', 
		'\b', '\x3', '\x2', '\x2', '\x2', '\x17', '\x1A', '\x5', '\x3', '\x2', 
		'\x2', '\x18', '\x1A', '\x5', '\x5', '\x3', '\x2', '\x19', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x19', '\x18', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x1C', '\n', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', '!', '\a', '$', '\x2', '\x2', '\x1E', ' ', 
		'\v', '\x2', '\x2', '\x2', '\x1F', '\x1E', '\x3', '\x2', '\x2', '\x2', 
		' ', '#', '\x3', '\x2', '\x2', '\x2', '!', '\"', '\x3', '\x2', '\x2', 
		'\x2', '!', '\x1F', '\x3', '\x2', '\x2', '\x2', '\"', '$', '\x3', '\x2', 
		'\x2', '\x2', '#', '!', '\x3', '\x2', '\x2', '\x2', '$', '%', '\a', '$', 
		'\x2', '\x2', '%', '\f', '\x3', '\x2', '\x2', '\x2', '&', '(', '\t', '\x4', 
		'\x2', '\x2', '\'', '&', '\x3', '\x2', '\x2', '\x2', '(', ')', '\x3', 
		'\x2', '\x2', '\x2', ')', '\'', '\x3', '\x2', '\x2', '\x2', ')', '*', 
		'\x3', '\x2', '\x2', '\x2', '*', '+', '\x3', '\x2', '\x2', '\x2', '+', 
		',', '\b', '\a', '\x2', '\x2', ',', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'-', '/', '\a', '\xF', '\x2', '\x2', '.', '-', '\x3', '\x2', '\x2', '\x2', 
		'.', '/', '\x3', '\x2', '\x2', '\x2', '/', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\x30', '\x33', '\a', '\f', '\x2', '\x2', '\x31', '\x33', '\a', 
		'\xF', '\x2', '\x2', '\x32', '.', '\x3', '\x2', '\x2', '\x2', '\x32', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x33', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '\x34', '\x32', '\x3', '\x2', '\x2', '\x2', '\x34', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\x10', '\x3', '\x2', '\x2', '\x2', '\n', 
		'\x2', '\x19', '\x1B', '!', ')', '.', '\x32', '\x34', '\x3', '\b', '\x2', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
